export  const Menu= [
    {
        id:1,
        image:"images/B1.jpg",
        name:"breakfast1",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:2,
        image:"images/B2.jpg",
        name:"breakfast2",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:3,
        image:"images/B3.jpg",
        name:"breakfast3",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:4,
        image:"images/B4.jpg",
        name:"breakfast4",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:5,
        image:"images/L1.jpg",
        name:"",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:6,
        image:"images/L2.jpg",
        name:"",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:7,
        image:"images/L3.jpg",
        name:"",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:8,
        image:"images/L4.jpg",
        name:"",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:9,
        image:"images/D1.jpg",
        name:"",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:10,
        image:"images/D2.jpg",
        name:"",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:11,
        image:"images/D3.jpg",
        name:"",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:12,
        image:"images/D4.jpg",
        name:"",
        category:"dinner",
        price:"",
        description:""
    },
    
]